### grp

# Course: _Introduction to R_:
1.  basics
2.  vectors
3.  matrices
4.  factors
5.  dataframes
6.  lists

## _1. R Basics_:
-  arithmetic:
    -  (addition) +
    -  (subtraction) -
    -  (multiplication) *
    -  (division) /
    -  (exponentiation) ^
    -  (modulo) %%
-  variables
-  basic data types:
    -  numerics (ex: decimals and integers => 4.5; 1)
    -  logical (ex: booleans => TRUE / FALSE)
    -  characters (ex: text => "string")
-  documentation:
    -  https://www.rdocumentation.org
    -  https://cran.r-project.org/index.html
    -  https://www.r-project.org/other-docs.html
    -  https://github.com/datacamp/Rdocumentation
-  help:
    -  ?<function_name> ... ex => ?factor

#### addition and subtraction

In [1]:
5 + 5 

5 - 5 

[1] 10

[1] 0

#### multiplication and division

In [2]:
3 * 5

(5 + 5) / 2 

[1] 15

[1] 5

#### exponential power

In [3]:
2^5

[1] 32

#### modulo (remainder)

In [4]:
28 %% 6

[1] 4

#### variables

In [5]:
my_var <- 4
x <- 42

print(my_var)
print(x)

[1] 4
[1] 42


#### variable calculations

In [6]:
my_apples <- 5
my_oranges <- 6
my_fruit <- my_apples + my_oranges

print(my_fruit)

[1] 11


#### other variable types

In [7]:
my_numeric <- 12.5
my_integer <- 1
my_logical <- TRUE
my_character <- "some text"

print(my_numeric)
print(my_integer)
print(my_logical)
print(my_character)

[1] 12.5
[1] 1
[1] TRUE
[1] "some text"


#### find variable type

In [8]:
print(class(my_numeric))
print(class(my_integer))
print(class(my_logical))
print(class(my_character))

[1] "numeric"
[1] "numeric"
[1] "logical"
[1] "character"


## _2. R Vectors_:
-  1D arrays that can contain numeric, character, and logical data
-  the elements in a vector all have the same type
-  ***R's first element in a vector has an index of 1 NOT 0!***
-  ***R includes "end" slice element in results => ex: c(2:5)***
-  logical comparison operators:
    -  <, >, <=, >=, ==, !=
-  basic vector functions:
    -  c()
    -  names()
    -  sum()
    -  mean()

#### vectors [lists]

In [9]:
numeric_vector <- c(1, 10, 49)
character_vector <- c("a", "b", "c")
boolean_vector <- c(TRUE, FALSE, TRUE)

In [10]:
poker_vector <- c(140, -50, 20, -120, 240)
roulette_vector <- c(-24, -50, 100, -350, 10)

#### naming vectors [index labels]

In [11]:
names(poker_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
names(roulette_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

#### naming vectors via variable

In [12]:
days_vector_variable <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
 
names(poker_vector) <- days_vector_variable
names(roulette_vector) <- days_vector_variable

In [13]:
print(poker_vector)
print(roulette_vector)

   Monday   Tuesday Wednesday  Thursday    Friday 
      140       -50        20      -120       240 
   Monday   Tuesday Wednesday  Thursday    Friday 
      -24       -50       100      -350        10 


#### vector element-wise calculations

In [14]:
A_vector <- c(1, 2, 3)
B_vector <- c(4, 5, 6)

total_vector <- A_vector + B_vector
total_vector_alternative <- c(1, 2, 3) + c(4, 5, 6)
  
total_vector
total_vector_alternative

[1] 5 7 9

[1] 5 7 9

In [15]:
total_daily <- poker_vector + roulette_vector
total_daily

Monday   Tuesday Wednesday  Thursday    Friday 
      116      -100       120      -470       250

#### vector aggregation

In [16]:
total_poker <- sum(poker_vector)
total_roulette <- sum(roulette_vector)
total_week <- total_poker + total_roulette

total_week # aggregation of poker and roulette

[1] -84

#### vector comparison

In [17]:
total_poker > total_roulette # more poker winnings than roulette winnings

[1] TRUE

#### vector element selection

In [18]:
print(poker_vector)

   Monday   Tuesday Wednesday  Thursday    Friday 
      140       -50        20      -120       240 


In [19]:
poker_wednesday <- poker_vector[3] # R vector indexes start at 1 NOT 0!
poker_wednesday

Wednesday 
       20

In [20]:
poker_midweek <- poker_vector[c(2, 3, 4)]
poker_midweek

Tuesday Wednesday  Thursday 
      -50        20      -120

#### vector element selection [slicing]

In [21]:
roulette_selection_vector <- roulette_vector[c(2:5)] # includes last slice element
roulette_selection_vector

Tuesday Wednesday  Thursday    Friday 
      -50       100      -350        10

#### vector element selection via index

In [22]:
poker_start <- poker_vector[c("Monday","Tuesday", "Wednesday")]
poker_start

Monday   Tuesday Wednesday 
      140       -50        20

#### vector average aggregation

In [23]:
mean(poker_start)

[1] 36.66667

#### logical comparison [boolean]

In [24]:
selection_vector <-  poker_vector > 0
print(selection_vector)

   Monday   Tuesday Wednesday  Thursday    Friday 
     TRUE     FALSE      TRUE     FALSE      TRUE 


#### return TRUE elements w/ value

In [25]:
selection_vector <- poker_vector > 0
poker_winning_days <- poker_vector[selection_vector]
print(poker_winning_days)

selection_vector <- roulette_vector > 0
roulette_winning_days <- roulette_vector[selection_vector]
print(roulette_winning_days)

   Monday Wednesday    Friday 
      140        20       240 
Wednesday    Friday 
      100        10 


## _3. R Matrices_:
-  2D arrays
-  collection of elements of the same data type organized into a fixed number of rows and columns
-  functions:
    -  matrix()
    -  colnames()
    -  rownames()
    -  rowSums()
    -  cbind()
    -  colSums()
    -  ls() => shows objects in current workspace
-  R workspace => https://www.statmethods.net/interface/workspace.html

#### create matrix by row

In [26]:
matrix(1:9, byrow=TRUE, nrow=3)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

#### create matrix by col

In [27]:
matrix(1:9, byrow=FALSE, nrow=3)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

#### combine vectors into matrices

In [28]:
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

box_office <- c(new_hope, empire_strikes, return_jedi)
star_wars_matrix <- matrix(box_office, byrow=TRUE, nrow=3)

star_wars_matrix

[,1]    [,2] 
[1,] 460.998 314.4
[2,] 290.475 247.9
[3,] 309.306 165.8

#### naming matrix

In [29]:
region <- c("US", "non-US")
titles <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

colnames(star_wars_matrix) <- region
rownames(star_wars_matrix) <- titles

star_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

#### matrix row aggregation

In [30]:
box_office <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)
star_wars_matrix <- matrix(box_office, nrow = 3, byrow = TRUE,
                           dimnames = list(c("A New Hope", "The Empire Strikes Back", "Return of the Jedi"), 
                                           c("US", "non-US")))
worldwide_vector <- rowSums(star_wars_matrix)

worldwide_vector

A New Hope The Empire Strikes Back      Return of the Jedi 
                775.398                 538.375                 475.106

#### add column(s) to matrix

In [31]:
all_wars_matrix <- cbind(star_wars_matrix, worldwide_vector)

all_wars_matrix

US      non-US worldwide_vector
A New Hope              460.998 314.4  775.398         
The Empire Strikes Back 290.475 247.9  538.375         
Return of the Jedi      309.306 165.8  475.106

#### add row(s) to matrix

In [32]:
box_office2 <- c(474.5, 552.5, 310.7, 338.7, 380.3, 468.5)
star_wars_matrix2 <- matrix(box_office2, nrow = 3, byrow = TRUE,
                           dimnames = list(c("The Phantom Menace", "Attack of the Clones", "Revenge of the Sith"), 
                                           c("US", "non-US")))
all_wars_matrix <- rbind(star_wars_matrix, star_wars_matrix2)

all_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8 
The Phantom Menace      474.500 552.5 
Attack of the Clones    310.700 338.7 
Revenge of the Sith     380.300 468.5

#### matrix col aggregation

In [33]:
total_revenue_vector <- colSums(all_wars_matrix)
  
print(total_revenue_vector)

      US   non-US 
2226.279 2087.800 


#### matrix element selection [row & col]

In [34]:
non_us_all <- all_wars_matrix[, 2] # select all rows and only 2nd column
mean(non_us_all)
  
non_us_some <- all_wars_matrix[1:2, 2] # select first 2 movies [rows] and only 2nd column
mean(non_us_some)

[1] 347.9667

[1] 281.15

#### matrix arithmetic

In [35]:
visitors <- all_wars_matrix / 5 # divide whole matrix by 5
  
visitors

US      non-US
A New Hope              92.1996  62.88
The Empire Strikes Back 58.0950  49.58
Return of the Jedi      61.8612  33.16
The Phantom Menace      94.9000 110.50
Attack of the Clones    62.1400  67.74
Revenge of the Sith     76.0600  93.70

In [36]:
ticket_vector <- c(5.0, 5.0, 6.0, 6.0, 7.0, 7.0, 4.0, 4.0, 4.5, 4.5, 4.9, 4.9)
ticket_prices_matrix <- matrix(ticket_vector, nrow = 6, byrow = TRUE,
dimnames = list(c("A New Hope", "The Empire Strikes Back", "Return of the Jedi",
                  "The Phantom Menace", "Attack of the Clones", "Revenge of the Sith"), 
                                           c("US", "non-US")))
visitors <- all_wars_matrix / ticket_prices_matrix
us_visitors <- visitors[, 1] # get all rows w/ only 1st column


visitors
mean(us_visitors)

US        non-US   
A New Hope               92.19960  62.88000
The Empire Strikes Back  48.41250  41.31667
Return of the Jedi       44.18657  23.68571
The Phantom Menace      118.62500 138.12500
Attack of the Clones     69.04444  75.26667
Revenge of the Sith      77.61224  95.61224

[1] 75.01339

## _4. R Factors_:
-  categorical variables are stored as **factor** data types
-  belong to a limited number of categories
-  types:
    -  nominal categorical variable:
        -  DOES NOT have a specific order or rank
        -  ex => "Armadillo", "Wombat", "Koala", "Platypus"
    -  ordinal categorical variable:
        -  DOES have a specific order or rank
        -  ex => "Freshman", "Sophomore", "Junior", "Senior"
-  ***R automatically assigns factors levels in alphabetical order if not specified***
-  functions:
    -  factor()
    -  levels()
    -  summary()

#### factor variable

In [37]:
sex_vector <- c("Male", "Female", "Female", "Male", "Male")

factor_sex_vector <- factor(sex_vector)

print(factor_sex_vector)

[1] Male   Female Female Male   Male  
Levels: Female Male


#### function help

In [38]:
# ?factor

#### nominal vs ordinal

In [39]:
animals_vector <- c("Elephant", "Giraffe", "Donkey", "Horse")
factor_animals_vector <- factor(animals_vector)
print(factor_animals_vector)

writeLines("====")

temperature_vector <- c("High", "Low", "High","Low", "Medium")
factor_temperature_vector <- factor(temperature_vector, order = TRUE, levels = c("Low", "Medium", "High"))
print(factor_temperature_vector)

[1] Elephant Giraffe  Donkey   Horse   
Levels: Donkey Elephant Giraffe Horse
====
[1] High   Low    High   Low    Medium
Levels: Low < Medium < High


#### factor levels

In [40]:
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)

levels(factor_survey_vector) <- c("Female", "Male")

print(factor_survey_vector)

[1] Male   Female Female Male   Male  
Levels: Female Male


#### factor summary

In [41]:
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
levels(factor_survey_vector) <- c("Female", "Male")
print(factor_survey_vector)

print(summary(survey_vector))
print(summary(factor_survey_vector))

[1] Male   Female Female Male   Male  
Levels: Female Male
   Length     Class      Mode 
        5 character character 
Female   Male 
     2      3 


#### compare nominal factor elements - ***R errors when trying to compare nominal factors***

In [42]:
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
levels(factor_survey_vector) <- c("Female", "Male")

male <- factor_survey_vector[1]
female <- factor_survey_vector[2]

male > female

Warning message in Ops.factor(male, female):
“‘>’ not meaningful for factors”

[1] NA

#### ordered (ordinal) factors

In [43]:
speed_vector <- c("medium", "slow", "slow", "medium", "fast")
factor_speed_vector <- factor(speed_vector,
                              ordered = TRUE,
                              levels = c("slow", "medium", "fast"))
print(factor_speed_vector)
summary(factor_speed_vector)

[1] medium slow   slow   medium fast  
Levels: slow < medium < fast


slow medium   fast 
     2      2      1

#### compare ordinal factor elements

In [44]:
da2 <- factor_speed_vector[2]
da5 <- factor_speed_vector[5]
da2 > da5

[1] FALSE

## _5. R DataFrames_:
-  variables as columns
-  observations as rows
-  2D objects
-  the elements within a column have the same types, but different columns can be different types
-  functions:
    -  head()
    -  tail()
    -  str() => structure of dataset
    -  data.frame()
    -  subset()
    -  order()

#### dataframe operations

In [45]:
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [46]:
tail(mtcars)

mpg  cyl disp  hp  drat wt    qsec vs am gear carb
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.7 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.9 1  1  5    2   
Ford Pantera L 15.8 8   351.0 264 4.22 3.170 14.5 0  1  5    4   
Ferrari Dino   19.7 6   145.0 175 3.62 2.770 15.5 0  1  5    6   
Maserati Bora  15.0 8   301.0 335 3.54 3.570 14.6 0  1  5    8   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.6 1  1  4    2

In [47]:
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


#### create dataframe

In [48]:
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

planets_df <- data.frame(name, type, diameter, rotation, rings)
str(planets_df)

'data.frame':	8 obs. of  5 variables:
 $ name    : Factor w/ 8 levels "Earth","Jupiter",..: 4 8 1 3 2 6 7 5
 $ type    : Factor w/ 2 levels "Gas giant","Terrestrial planet": 2 2 2 2 1 1 1 1
 $ diameter: num  0.382 0.949 1 0.532 11.209 ...
 $ rotation: num  58.64 -243.02 1 1.03 0.41 ...
 $ rings   : logi  FALSE FALSE FALSE FALSE TRUE TRUE ...


#### dataframe index selection

In [49]:
print(planets_df[1, 3]) # prints 1 row and 3rd col
print(planets_df[4, ]) # prints 4th row and every col

[1] 0.382
  name               type diameter rotation rings
4 Mars Terrestrial planet    0.532     1.03 FALSE


In [50]:
planets_df[1:5, "diameter"] # prints first 5 observations for diameter col

[1]  0.382  0.949  1.000  0.532 11.209

In [51]:
rings_vector <- planets_df$rings # or planets_df[, "rings"]
rings_vector

planets_df[, "rings"]

[1] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE

[1] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE

#### dataframe subset [filter]

In [52]:
planets_df[rings_vector, ] # prints all rows where rings = TRUE

name    type      diameter rotation rings
5 Jupiter Gas giant 11.209    0.41    TRUE 
6 Saturn  Gas giant  9.449    0.43    TRUE 
7 Uranus  Gas giant  4.007   -0.72    TRUE 
8 Neptune Gas giant  3.883    0.67    TRUE

In [53]:
# more efficient filter method
subset(planets_df, diameter < 1)

name    type               diameter rotation rings
1 Mercury Terrestrial planet 0.382      58.64  FALSE
2 Venus   Terrestrial planet 0.949    -243.02  FALSE
4 Mars    Terrestrial planet 0.532       1.03  FALSE

#### ordering

In [54]:
a <- c(100, 10, 1000)
order(a)
a[order(a)]

[1] 2 1 3

[1]   10  100 1000

#### sort dataframe by col

In [55]:
positions <- order(planets_df$diameter)
planets_df[positions, ] # DESC order is default

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
8 Neptune Gas giant           3.883      0.67   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
5 Jupiter Gas giant          11.209      0.41   TRUE

## _6. R Lists_:
-  contain a variety of objects (ex: vectors, matrices, dataframes, lists, etc) under one name
-  functions:
    -  list()
    -  c() => can be used to add elements to lists

#### create list

In [56]:
my_vector <- 1:10 
my_matrix <- matrix(1:9, ncol = 3)
my_df <- mtcars[1:10,]

my_list <- list(my_vector, my_matrix, my_df)

In [57]:
my_vector

[1]  1  2  3  4  5  6  7  8  9 10

In [58]:
my_matrix

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [59]:
my_df

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360        14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D         24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230          22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280          19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4

In [60]:
my_list

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

#### name list

In [61]:
my_list <- list(vec = my_vector,
                mat = my_matrix,
                df = my_df)
my_list

$vec
 [1]  1  2  3  4  5  6  7  8  9 10

$mat
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$df
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

#### selecting elements from list

In [62]:
my_list[1]
my_list[[1]][1] # prints out 1st element of $vec
my_list["mat"]
my_list$df

$vec
 [1]  1  2  3  4  5  6  7  8  9 10

[1] 1

$mat
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360        14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D         24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230          22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280          19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4

#### add elements to current list

In [63]:
my_list_full <- c(my_list, year = 1980)
str(my_list_full)

List of 4
 $ vec : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ mat : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
 $ df  :'data.frame':	10 obs. of  11 variables:
  ..$ mpg : num [1:10] 21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2
  ..$ cyl : num [1:10] 6 6 4 6 8 6 8 4 4 6
  ..$ disp: num [1:10] 160 160 108 258 360 ...
  ..$ hp  : num [1:10] 110 110 93 110 175 105 245 62 95 123
  ..$ drat: num [1:10] 3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92
  ..$ wt  : num [1:10] 2.62 2.88 2.32 3.21 3.44 ...
  ..$ qsec: num [1:10] 16.5 17 18.6 19.4 17 ...
  ..$ vs  : num [1:10] 0 0 1 1 0 1 0 1 1 1
  ..$ am  : num [1:10] 1 1 1 0 0 0 0 0 0 0
  ..$ gear: num [1:10] 4 4 4 3 3 3 3 4 4 4
  ..$ carb: num [1:10] 4 4 1 1 2 1 4 2 2 4
 $ year: num 1980


### grp